# Generated by Django 3.2.2 on 2021-05-16 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='datecompleat',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
